version: '3.8'

services:
  backend:
    build:
      context: ./backend
    # env_file:
    #   - .env
    ports:
      - "5001:5001"  
    environment:
      - MONGODB_URI=mongodb+srv://shivansh:Shivansh31415@chat-app.tz901x5.mongodb.net/chatappDB?retryWrites=true&w=majority&appName=chat-app
      - JWT_SECRET=4cca6db57518691d646ae994a86658a814893488ffc61bee8e3f0af57260aeffda131d15625b464574c6c8e6b6898697e36a89851b4c21728a1e7964f36a13cf
      - CLOUDINARY_CLOUD_NAME=dw1uslzor
      - CLOUDINARY_API_KEY=433557261253722
      - CLOUDINARY_API_SECRET=Cu5505YZjMcrrSEj052nEI1Qc3A
      - NODE_ENV=production
      - PORT=5001
    restart: unless-stopped
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=http://51.21.200.151:5001/api
    depends_on:
      - backend
  mongo:
    image: mongo:5
    container_name: chatapp_mongo
    ports:
      - "27017:27017"
#     volumes:
#       # - mongo_data:/data/db

# volumes:
#   mongo_data:
